Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/wily64"
  config.vm.synced_folder "../", "/word_max"
  config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
end
